language: node_js
node_js:
  - 8
install:
  - cd $TRAVIS_BUILD_DIR
  - "yarn"
script:
  - cd $TRAVIS_BUILD_DIR
  - "yarn test"
  - "yarn build"
  - "yarn copy-manifest"
  - "yarn build-storybook"
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - "cd dist"
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_PAGES_TOKEN
    local-dir: ".storybook-build"
    on:
      branch: development
  - provider: surge
    skip-cleanup: true
    project: ./.storybook-build
    domain: awc-$TRAVIS_COMMIT.surge.sh
    on:
      all_branches: true
